2022-07-08 17:36:03,763 ERROR: Exception on /index [GET] [in /mnt/e/microblog/venv/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/mnt/e/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/e/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/e/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/e/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/mnt/e/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/mnt/e/microblog/app/routes.py", line 160, in index
    posts = current_user.followed_posts().paginage(
AttributeError: 'BaseQuery' object has no attribute 'paginage'
2022-07-08 17:36:05,564 ERROR: Exception on /index [GET] [in /mnt/e/microblog/venv/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/mnt/e/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/e/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/e/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/e/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/mnt/e/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/mnt/e/microblog/app/routes.py", line 160, in index
    posts = current_user.followed_posts().paginage(
AttributeError: 'BaseQuery' object has no attribute 'paginage'
2022-07-08 17:36:10,105 ERROR: Exception on /index [GET] [in /mnt/e/microblog/venv/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/mnt/e/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/e/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/e/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/e/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/mnt/e/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/mnt/e/microblog/app/routes.py", line 160, in index
    posts = current_user.followed_posts().paginage(
AttributeError: 'BaseQuery' object has no attribute 'paginage'
2022-07-08 17:36:36,083 INFO: Microblog startup [in /mnt/e/microblog/app/__init__.py:44]
2022-07-08 17:45:05,251 INFO: Microblog startup [in /mnt/e/microblog/app/__init__.py:44]
2022-07-08 17:45:10,413 ERROR: Exception on /index [GET] [in /mnt/e/microblog/venv/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/mnt/e/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/e/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/e/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/e/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/mnt/e/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/mnt/e/microblog/app/routes.py", line 167, in index
    return render_template("index.html", title='Home', form=form,
  File "/mnt/e/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 149, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/mnt/e/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/mnt/e/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/mnt/e/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/mnt/e/microblog/venv/lib/python3.8/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/mnt/e/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/mnt/e/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/mnt/e/microblog/app/templates/index.html", line 26, in template
    {% endblock %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endblock'. You probably made a nesting mistake. Jinja is expecting this tag, but currently looking for 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
2022-07-08 17:45:47,550 INFO: Microblog startup [in /mnt/e/microblog/app/__init__.py:44]
2022-07-08 17:52:03,796 INFO: Microblog startup [in /mnt/e/microblog/app/__init__.py:44]
2022-07-08 17:52:12,893 ERROR: Exception on /user/tim [GET] [in /mnt/e/microblog/venv/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/mnt/e/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/e/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/e/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/e/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/mnt/e/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/mnt/e/microblog/app/routes.py", line 75, in user
    posts = user.posts.oder_by(Post.timetsamp.desc()).paginate(
AttributeError: 'AppenderBaseQuery' object has no attribute 'oder_by'
2022-07-08 17:52:35,551 INFO: Microblog startup [in /mnt/e/microblog/app/__init__.py:44]
2022-07-08 17:52:39,449 ERROR: Exception on /user/tim [GET] [in /mnt/e/microblog/venv/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/mnt/e/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/e/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/e/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/e/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/mnt/e/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/mnt/e/microblog/app/routes.py", line 75, in user
    posts = user.posts.order_by(Post.timetsamp.desc()).paginate(
AttributeError: type object 'Post' has no attribute 'timetsamp'
2022-07-08 17:52:55,656 INFO: Microblog startup [in /mnt/e/microblog/app/__init__.py:44]
